version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb-user:
    image: mongo

  mongodb-wallet:
    image: mongo

  mongodb-product:
    image: mongo

  user-service:
    image: joshiravi1991/microservice_rabbitmq:user-service-uat
     ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
      - mongodb-user
    environment:
      RABBITMQ_URL: amqp://rabbitmq

  wallet-service:
    image: joshiravi1991/microservice_rabbitmq:wallet-service-uat
    depends_on:
      - rabbitmq
      - mongodb-wallet
    environment:
      RABBITMQ_URL: amqp://rabbitmq

  product-service:
    image: joshiravi1991/microservice_rabbitmq:product-service-uat
    depends_on:
      - mongodb-product
